# Generated by Django 2.0 on 2017-12-27 20:23

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    World = apps.get_model("game", "World")
    db_alias = schema_editor.connection.alias
    World.objects.using(db_alias).create(
        name="World 1"
    )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
