# Generated by Django 2.0 on 2017-12-28 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20171227_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HQ', 'Headquarters'), ('WM', 'Wood Mine'), ('CM', 'Clay Mine'), ('IM', 'Iron Mine'), ('WH', 'Warehouse')], default='HQ', max_length=2)),
                ('level', models.IntegerField(default=1)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Village')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('village', 'type')},
        ),
    ]
