# Generated by Django 2.0 on 2017-12-28 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20171228_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='_clay',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='village',
            name='_iron',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='village',
            name='_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='village',
            name='_wood',
            field=models.IntegerField(default=500),
        ),
    ]
