# Generated by Django 2.0 on 2017-12-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20171228_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='_clay',
            field=models.DecimalField(decimal_places=6, default=500, max_digits=16),
        ),
        migrations.AlterField(
            model_name='village',
            name='_iron',
            field=models.DecimalField(decimal_places=6, default=500, max_digits=16),
        ),
        migrations.AlterField(
            model_name='village',
            name='_wood',
            field=models.DecimalField(decimal_places=6, default=500, max_digits=16),
        ),
    ]
