# Generated by Django 2.0 on 2017-12-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20171228_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.CharField(choices=[('HQ', 'Headquarters'), ('WM', 'Wood Mine'), ('CM', 'Clay Mine'), ('IM', 'Iron Mine'), ('WH', 'Warehouse'), ('FM', 'Farm'), ('BR', 'Barracks')], default='HQ', max_length=2),
        ),
    ]
