# Generated by Django 2.0 on 2017-12-28 04:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20171228_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HQ', 'Headquarters'), ('WM', 'Wood Mine'), ('CM', 'Clay Mine'), ('IM', 'Iron Mine'), ('WH', 'Warehouse'), ('FM', 'Farm'), ('BR', 'Barracks'), ('RP', 'Rally Point')], max_length=2)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Village')),
            ],
        ),
    ]
