# Generated by Django 2.0 on 2017-12-28 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20171228_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildtask',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
