# Generated by Django 2.0 on 2017-12-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_buildtask_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Troop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SP', 'Spearman'), ('AX', 'Axeman')], default='SP', max_length=2)),
                ('amount', models.IntegerField()),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troops', to='game.Village')),
            ],
        ),
        migrations.AlterField(
            model_name='building',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='game.Village'),
        ),
        migrations.AlterField(
            model_name='buildtask',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildqueue', to='game.Village'),
        ),
    ]
