# Generated by Django 2.0 on 2017-12-28 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20171228_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='game.Village')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='game.Village')),
            ],
        ),
        migrations.AlterField(
            model_name='troop',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='troops', to='game.Village'),
        ),
        migrations.AddField(
            model_name='troop',
            name='attack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='troops', to='game.Attack'),
        ),
    ]
