# Generated by Django 2.0 on 2017-12-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20171228_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='returning',
            field=models.BooleanField(default=False),
        ),
    ]
