# Generated by Django 2.0 on 2017-12-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_auto_20171228_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='trooptask',
            name='step_time',
            field=models.DateTimeField(null=True),
        ),
    ]
