# Generated by Django 2.0 on 2017-12-29 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_trooptask_step_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='world',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together={('x', 'y', 'world')},
        ),
    ]
