# Generated by Django 2.0 on 2017-12-29 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20171228_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villages', to=settings.AUTH_USER_MODEL),
        ),
    ]
