# Generated by Django 2.0 on 2017-12-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_auto_20171228_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.CharField(choices=[('HQ', 'Headquarters'), ('WM', 'Wood Mine'), ('CM', 'Clay Mine'), ('IM', 'Iron Mine'), ('WH', 'Warehouse'), ('FM', 'Farm'), ('BR', 'Barracks'), ('RP', 'Rally Point'), ('ST', 'Stable')], default='HQ', max_length=2),
        ),
        migrations.AlterField(
            model_name='buildtask',
            name='type',
            field=models.CharField(choices=[('HQ', 'Headquarters'), ('WM', 'Wood Mine'), ('CM', 'Clay Mine'), ('IM', 'Iron Mine'), ('WH', 'Warehouse'), ('FM', 'Farm'), ('BR', 'Barracks'), ('RP', 'Rally Point'), ('ST', 'Stable')], max_length=2),
        ),
        migrations.AlterField(
            model_name='troop',
            name='type',
            field=models.CharField(choices=[('SP', 'Spearman'), ('SW', 'Swordsman'), ('AX', 'Axeman'), ('AR', 'Archer')], default='SP', max_length=2),
        ),
        migrations.AlterField(
            model_name='trooptask',
            name='type',
            field=models.CharField(choices=[('SP', 'Spearman'), ('SW', 'Swordsman'), ('AX', 'Axeman'), ('AR', 'Archer')], max_length=2),
        ),
    ]
