# Generated by Django 2.0 on 2017-12-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_auto_20171229_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='loyalty',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='troop',
            name='type',
            field=models.CharField(choices=[('SP', 'Spearman'), ('SW', 'Swordsman'), ('AX', 'Axeman'), ('AR', 'Archer'), ('NB', 'Noble')], default='SP', max_length=2),
        ),
        migrations.AlterField(
            model_name='trooptask',
            name='type',
            field=models.CharField(choices=[('SP', 'Spearman'), ('SW', 'Swordsman'), ('AX', 'Axeman'), ('AR', 'Archer'), ('NB', 'Noble')], max_length=2),
        ),
    ]
