# Generated by Django 2.0 on 2017-12-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_auto_20171229_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='loyalty',
        ),
        migrations.AddField(
            model_name='village',
            name='_loyalty',
            field=models.DecimalField(decimal_places=6, default=100, max_digits=9),
        ),
    ]
