# Generated by Django 2.0 on 2017-12-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_auto_20171229_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='returning',
        ),
        migrations.AddField(
            model_name='attack',
            name='type',
            field=models.CharField(choices=[('AT', 'Attack'), ('RT', 'Return')], default='AT', max_length=2),
            preserve_default=False,
        ),
    ]
