# Generated by Django 2.0 on 2017-12-29 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_auto_20171229_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='troop',
            name='original',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_troops', to='game.Village'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='type',
            field=models.CharField(choices=[('AT', 'Attack'), ('RT', 'Return'), ('SP', 'Support')], max_length=2),
        ),
        migrations.AlterField(
            model_name='troop',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_troops', to='game.Village'),
        ),
    ]
