# Generated by Django 2.0 on 2017-12-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_auto_20171229_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.CharField(choices=[('HQ', 'Headquarters'), ('WM', 'Wood Mine'), ('CM', 'Clay Mine'), ('IM', 'Iron Mine'), ('WH', 'Warehouse'), ('FM', 'Farm'), ('BR', 'Barracks'), ('RP', 'Rally Point'), ('ST', 'Stable'), ('AC', 'Academy')], default='HQ', max_length=2),
        ),
        migrations.AlterField(
            model_name='buildtask',
            name='type',
            field=models.CharField(choices=[('HQ', 'Headquarters'), ('WM', 'Wood Mine'), ('CM', 'Clay Mine'), ('IM', 'Iron Mine'), ('WH', 'Warehouse'), ('FM', 'Farm'), ('BR', 'Barracks'), ('RP', 'Rally Point'), ('ST', 'Stable'), ('AC', 'Academy')], max_length=2),
        ),
    ]
