# Generated by Django 2.0 on 2017-12-30 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_auto_20171230_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trooptask',
            name='village',
        ),
        migrations.AddField(
            model_name='trooptask',
            name='building',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='troopqueue', to='game.Building'),
            preserve_default=False,
        ),
    ]
