# Generated by Django 2.0 on 2017-12-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_auto_20171230_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troop',
            name='type',
            field=models.CharField(choices=[('SP', 'Spearman'), ('SW', 'Swordsman'), ('AX', 'Axeman'), ('AR', 'Archer'), ('SC', 'Scout'), ('NB', 'Noble')], max_length=2),
        ),
    ]
