# Generated by Django 2.0 on 2017-12-30 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_auto_20171230_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='game.World'),
        ),
    ]
