# Generated by Django 2.0 on 2017-12-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_auto_20171230_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.CharField(choices=[('AC', 'Academy'), ('BR', 'Barracks'), ('CM', 'Clay Mine'), ('FM', 'Farm'), ('HQ', 'Headquarters'), ('IM', 'Iron Mine'), ('RP', 'Rally Point'), ('ST', 'Stable'), ('WA', 'Wall'), ('WH', 'Warehouse'), ('WM', 'Wood Mine'), ('WS', 'Workshop')], default='HQ', max_length=2),
        ),
        migrations.AlterField(
            model_name='buildtask',
            name='type',
            field=models.CharField(choices=[('AC', 'Academy'), ('BR', 'Barracks'), ('CM', 'Clay Mine'), ('FM', 'Farm'), ('HQ', 'Headquarters'), ('IM', 'Iron Mine'), ('RP', 'Rally Point'), ('ST', 'Stable'), ('WA', 'Wall'), ('WH', 'Warehouse'), ('WM', 'Wood Mine'), ('WS', 'Workshop')], max_length=2),
        ),
    ]
