# Generated by Django 2.0 on 2017-12-31 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_auto_20171231_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='completed',
        ),
        migrations.AlterField(
            model_name='quest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to=settings.AUTH_USER_MODEL),
        ),
    ]
