# Generated by Django 2.0 on 2018-01-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0042_auto_20171231_1413'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['village', 'type'], name='game_buildi_village_5f8a04_idx'),
        ),
    ]
