language: python
python:
    - '3.5'
sudo: false
cache:
    directories:
        - "$HOME/.cache/pip"
install:
    - pip install pip flake8 -r requirements.txt
script:
    - flake8 --exclude=*/migrations/* villagebattles
    - ./manage.py test
