# Generated by Django 2.0 on 2017-12-31 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_auto_20171230_1813'),
        ('tribes', '0002_member'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tribe',
            unique_together={('name', 'world')},
        ),
    ]
