# Generated by Django 2.0 on 2017-12-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0003_auto_20171230_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('OW', 'Owner'), ('ME', 'Member')], default='ME', max_length=2),
            preserve_default=False,
        ),
    ]
