# Generated by Django 2.0 on 2018-02-15 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0004_member_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('tribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='tribes.Tribe')),
            ],
        ),
    ]
