# Generated by Django 2.0 on 2017-12-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0002_member'),
        ('users', '0002_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tribes',
            field=models.ManyToManyField(related_name='members', through='tribes.Member', to='tribes.Tribe'),
        ),
    ]
